name: Build userspace
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - planck
          - crkbd

    steps:
    - name: Checkout QMK
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        fetch-depth: 1
        persist-credentials: false
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}
        fetch-depth: 1
        persist-credentials: false

    - name: Build firmware
      run: qmk compile "users/${{ github.actor }}/${{ matrix.keyboard }}.json"

    - name: Archive firmware
      uses: actions/upload-artifact@v2
      with:
        name: "${{ matrix.keyboard }}_firmware"
        retention-days: 2
        path: |
          *.hex
          *.bin
      continue-on-error: true
